site_name: MIDI Scripter
site_url: https://maboroshy.github.io/midi-scripter
repo_url: https://github.com/Maboroshy/midi-scripter

nav:
    - Readme: index.md  # Copied from README.md by GitHub action on publish
    - Overview: overview.md

    - API Documentation:
        - Midi:
            - Ports: api/midi_port.md
            - Messages: api/midi_msg.md
            - Utils: api/midi_note_data.md  
        
        - Open Sound Control:
            - Ports: api/osc_port.md
            - Message: api/osc_msg.md
        
        - Keyboard:
            - Ports: api/key_port.md
            - Message: api/key_msg.md

        - Mouse:
            - Ports: api/mouse_port.md
            - Message: api/mouse_msg.md

        - GUI Widgets:
            - Text: api/gui_text.md
            - Buttons: api/gui_buttons.md
            - List Selector: api/gui_list.md
            - Layout: api/gui_layout.md
            - GUI Event Message: api/gui_msg.md

        - Starters: api/starters.md
        
        - Logging: api/logging.md
        
        - Extra ports:
            - Metronome: api/metronome_port.md
            - File System Events:
                - Port: api/fs_port.md
                - Message: api/fs_event_msg.md
            - Midi Ports Changes: api/midi_ports_changed.md
        
        - Base Classes:
            - Ports: api/base_ports.md
            - Message: api/base_msg.md
            - GUI Widget: api/base_gui_widget.md
theme:
    name: material
    locale: en
    logo: icon.svg
    favicon: icon.svg

    features:
        - navigation.instant
        - navigation.sections

    icon:
      repo: fontawesome/brands/github

    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            preload_modules:
              - midiscripter
            docstring_section_style: 'list'
            merge_init_into_class: true
            line_length: 80
            
            inherited_members: true
            members_order: source
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            
            filters:
              - "!^_"
              - "!^__"

            show_source: false
            show_root_heading: true
            show_root_full_path: false

            separate_signature: true
            show_signature_annotations: true
            
            extensions:
              - griffe_inherited_docstrings

watch:
  - .
