import enum


class AttrEnum(enum.StrEnum):
    __repr = None

    def __repr__(self):
        if self.__repr is None:
            self.__repr = f'{self.__class__.__name__}.{self.name}'
        return self.__repr


class Msg:
    """The data object generated by input port that is sent as an argument to its subscribed calls
    and can be sent with an output port"""

    type: str
    """Message type description for filtering and representation"""

    __match_args__: tuple[str] = ('type',)

    _log_color: str | None = 'blue'
    _log_show_link: bool = True

    def __init__(self, type: str):
        """
        Args:
            type: Message distinctive type
        """
        self.type = type

    def __repr__(self):
        return f'{self.__class__.__name__}({", ".join(map(repr, self._as_tuple()))})'

    def __str__(self):
        return ' | '.join([str(value) for value in self._as_tuple() if value is not None])

    def __eq__(self, other_msg: 'Msg'):
        return type(self) is type(other_msg) and self._as_tuple() == other_msg._as_tuple()

    def __copy__(self):
        return type(self)(*self._as_tuple())

    def matches(self, *conditions_args, **conditions_kwargs) -> bool:
        """Checks if message's attributes match all provided attribute conditions:

        1. If condition is `None` or omitted, it matches anything.

        2. If condition equals attribute, it matches the attribute.

        3. If condition is a container (list, tuple) and contains the attribute, it matches the attribute.

        Use [`Not(condition)`][midiscripter.base.match_conditions.Not] to invert condition matching.
        Use [`Glob(pattern)`][midiscripter.base.match_conditions.Glob]
        or [`Regex(pattern)`][midiscripter.base.match_conditions.Regex] for string pattern matching.

        Returns:
            `True` if all attributes match, `False` if any does not match
        """
        attr_values = self._as_tuple()

        for index, condition in enumerate(conditions_args):
            if condition is not None and condition != attr_values[index]:
                return False

        if conditions_kwargs:
            for parameter_name, condition in conditions_kwargs.items():
                try:
                    if condition is not None or condition != getattr(self, parameter_name):
                        return False
                except AttributeError:
                    return False

        return True

    def _as_tuple(self) -> tuple:
        """Converts message to a tuple based on message's __match_args__ class attribute

        Returns:
            Tuple with values of attributes specified in __match_args__ class attribute
        """
        return tuple(getattr(self, attr_name) for attr_name in self.__match_args__)
